### ISSUE TITLE
missing json schema files?

### ISSUE THREAD

**Issue by rupello** [saubury/plane-kafka#1]
When running the setup I get the error below - I think these files are missing?
```
root@confluent:/scripts# ./02_do_load 
cat: icao-to-aircraft.json: No such file or directory
cat: callsign-details.json: No such file or directory
```

**Comment by saubury** [comment]
Hi

Data files _callsign-details.json _and_  icao-to-aircraft.json_ are both required, but I can not distribute them.

I generated them use sources found at https://openflights.org/data.html

I've added some sample files to get new starters going

I've updated  02_do_load with a basic check so hopefully this is more obvious in the future

I've updated  02_do_load
