### ISSUE TITLE
run scritp/04_elastic_dynamic_template failed to connect HOST:9200

### ISSUE THREAD

**Issue by taskx6004** [saubury/plane-kafka#5]
Sorry it's my first-time contact with ELK, when I was running script 04, how to setup the elasticsearch (server?) , as i assume it's already running in docker accroding to docker-compose file.

**Comment by saubury** [comment]
Yes - it should be running via docker

You can check the status with `docker-compose ps`

You'll do most of the setup via Kibana (a graphical UI for elastic) - Navigate to http://localhost:5601
